name: Publish Docker Image

on:
  push:
    tags:
      - "[0-9]*"

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Determine if the tag was created on the default branch
        run: |
          echo "$GITHUB_REF_NAME"
          COMMIT=$(git rev-parse $GITHUB_REF_NAME~0)
          COMMIT2=$(git rev-parse $GITHUB_REF_NAME)
          echo "github_sha=$GITHUB_SHA"
          echo "$COMMIT"
          echo "$COMMIT2"
          echo "BRANCH=$(git branch --contains $COMMIT)"
          echo "BRANCH2=$(git branch --contains $COMMIT2)"
          echo "BRANCH3=$(git branch --contains $GITHUB_SHA)"
          echo "$BRANCH"
          echo "$BRANCH2"
          echo "$BRANCH3"
          echo "_branch=${GITHUB_REF#refs/heads/}"
          echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")"

      - name: Docker meta service name for DockerHub development image
        id: docker_meta_img_dev
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/dev
          tags: |
            type=raw,value=latest,enable=${{ github.event.repository.default_branch == "main" }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Docker meta service name for DockerHub production image
        id: docker_meta_img_prod
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.event.repository.default_branch == "main" }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into DockerHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }} development image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          target: development
          tags: ${{ steps.docker_meta_img_dev.outputs.tags }}
          labels: ${{ steps.docker_meta_img_dev.outputs.labels }}

      - name: Build and push ${{ github.repository }} production image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          target: production
          tags: ${{ steps.docker_meta_img_prod.outputs.tags }}
          labels: ${{ steps.docker_meta_img_prod.outputs.labels }}
