name: Publish Docker Image

on:
  push:
    tags:
      - "[0-9]*"

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Determine if the tag was created on the default branch
        run: |
          COMMIT=$(git rev-list -1 $GITHUB_REF_NAME)
          echo "tag_commit=$COMMIT" >> $GITHUB_ENV
          BRANCHES=$(git branch --contains tag_commit)
          echo "tag_branch=$BRANCHES"
          echo "github_ref=$GITHUB_REF"

      - name: Docker meta service name for DockerHub development image
        id: docker_meta_img_dev
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/dev
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Docker meta service name for DockerHub production image
        id: docker_meta_img_prod
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into DockerHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }} development image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          target: development
          tags: ${{ steps.docker_meta_img_dev.outputs.tags }}
          labels: ${{ steps.docker_meta_img_dev.outputs.labels }}

      - name: Build and push ${{ github.repository }} production image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          target: production
          tags: ${{ steps.docker_meta_img_prod.outputs.tags }}
          labels: ${{ steps.docker_meta_img_prod.outputs.labels }}
